name: aflow-school
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - scipy
  - pip
  - ipywidgets
  - jupyter-offlinenotebook
  - jupyter-resource-usage
  - jupyterlab
  - jupyterhub-singleuser
  - notebook
  - nteract_on_jupyter


