#!/usr/bin/env python3
# postBuild for AFLOW SCHOOL
# download and setup aflow binary

import subprocess
import sys
from pathlib import Path
from urllib import request
print("Preparing AFLOW SCHOOL environment")

def run(*args, **kwargs):
    # Run a command, echoing the args; fails hard if something goes wrong
    print("\t", " ".join(args), flush=True)
    return_code = subprocess.call(args, **kwargs)
    if return_code != 0:
        print("\nERROR", return_code, " ".join(args))
        sys.exit(return_code)

# folder setup
print("  Creating Folders")
bin_folder = Path("~/.local/bin")
setup_folder = Path("~/.setup")

bin_folder = bin_folder.expanduser().resolve()
bin_folder.mkdir(parents=True, exist_ok=True)

setup_folder = setup_folder.expanduser().resolve()
setup_folder.mkdir(parents=True, exist_ok=True)

# binary setup
print("  Installing prebuild aflow")
aflow_prebuild_url = "https://github.com/aflow-org/aflow/releases/download/v4.0.5/aflow-4.0.5-ubuntu24-amd64.sh"
aflow_path = bin_folder / "aflow"
aflow_setup_path = setup_folder / "aflow.sh"
print(f"    Downloading {aflow_prebuild_url} to {aflow_setup_path.absolute()}", flush=True)
local_filename, headers = request.urlretrieve(aflow_prebuild_url, filename=aflow_setup_path.absolute())
print(local_filename, flush=True)
print(headers, flush=True)
aflow_setup_path.touch()
aflow_setup_path.chmod(0o777)
#
# run("aflow.sh", "--skip-license", f"--prefix={bin_folder.absolute()}", cwd=str(setup_folder))
#
# # test if install worked
# run('aflow', '--version', cwd='/tmp')

print("Preparations done!")
